# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OLAP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completionrate',
            old_name='show_Director',
            new_name='director_Name',
        ),
    ]
